server:
  port: 3000

spring:
  application:
    name: client-zuul

zuul:
  routes:
    client-system:
      path: /eli/**
      serciceId: client-system
      strip-prefix: true
  host:
    connect-timeout-millis: 60000

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 600000

ribbon:
  ReadTimeout: 50000
  ConnectTimeout: 50000
