server:
  port: 3000

spring:
  application:
    name: client-zuul

zuul:
  routes:
    client-system:
      path: /eli/**
      serciceId: client-system
      strip-prefix: true
  host:
    connect-timeout-millis: 60000
