server:
  port: 3000

spring:
  application:
    name: client-zuul

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:7070/eureka/

zuul:
  routes:
    client-system:
      path: /eli/**
      serciceId: client-system
      strip-prefix: true
  host:
    connect-timeout-millis: 60000
